package com.king.dubbo.weixin.dao;



import com.king.dubbo.entities.model.wx.WxActivityAward;
import com.king.dubbo.entities.model.wx.WxActivityAwardExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxActivityAwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxActivityAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxActivityAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxActivityAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxActivityAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxActivityAward> selectByExample(WxActivityAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxActivityAward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxActivityAward record, @Param("example") WxActivityAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxActivityAward record, @Param("example") WxActivityAwardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxActivityAward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxActivityAward record);
}