package com.king.dubbo.weixin.dao;

import java.util.List;

import com.king.dubbo.entities.model.wx.WxActivityCount;
import com.king.dubbo.entities.model.wx.WxActivityCountExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WxActivityCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxActivityCount> selectByExample(WxActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxActivityCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxActivityCount record, @Param("example") WxActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxActivityCount record, @Param("example") WxActivityCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxActivityCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxActivityCount record);
}