package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxArticleInfo;
import com.king.dubbo.entities.model.wx.WxArticleInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxArticleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int countByExample(WxArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int deleteByExample(WxArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int insert(WxArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int insertSelective(WxArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    List<WxArticleInfo> selectByExample(WxArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    WxArticleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxArticleInfo record, @Param("example") WxArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int updateByExample(@Param("record") WxArticleInfo record, @Param("example") WxArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int updateByPrimaryKeySelective(WxArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    int updateByPrimaryKey(WxArticleInfo record);

    /**
     * @description 查询该编号的对应的所有的图文消息
     * @author shenwang
     * @return
     */
    public List<WxArticleInfo> getAllArticleInfoByCode(@Param("code") String code);
}