package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxAssignmentActivity;
import com.king.dubbo.entities.model.wx.WxAssignmentActivityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxAssignmentActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxAssignmentActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxAssignmentActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxAssignmentActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxAssignmentActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxAssignmentActivity> selectByExample(WxAssignmentActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxAssignmentActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxAssignmentActivity record, @Param("example") WxAssignmentActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxAssignmentActivity record, @Param("example") WxAssignmentActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxAssignmentActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_activity_assignment
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxAssignmentActivity record);
}