package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxMenuConfig;
import com.king.dubbo.entities.model.wx.WxMenuConfigExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxMenuConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int countByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int deleteByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int insert(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int insertSelective(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    List<WxMenuConfig> selectByExample(WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    WxMenuConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxMenuConfig record, @Param("example") WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int updateByExample(@Param("record") WxMenuConfig record, @Param("example") WxMenuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int updateByPrimaryKeySelective(WxMenuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_menu_config
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    int updateByPrimaryKey(WxMenuConfig record);


}