package com.king.dubbo.weixin.dao;

import java.util.List;

import com.king.dubbo.entities.model.wx.WxMsgLog;
import com.king.dubbo.entities.model.wx.WxMsgLogExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WxMsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxMsgLog> selectByExampleWithBLOBs(WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxMsgLog> selectByExample(WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxMsgLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxMsgLog record, @Param("example") WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") WxMsgLog record, @Param("example") WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxMsgLog record, @Param("example") WxMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(WxMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_msg_log
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxMsgLog record);
}