package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxReplyTemplateInfo;
import com.king.dubbo.entities.model.wx.WxReplyTemplateInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface WxReplyTemplateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxReplyTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxReplyTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxReplyTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxReplyTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxReplyTemplateInfo> selectByExample(WxReplyTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxReplyTemplateInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxReplyTemplateInfo record, @Param("example") WxReplyTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxReplyTemplateInfo record, @Param("example") WxReplyTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxReplyTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_template
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxReplyTemplateInfo record);
}