package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxTemplateInfo;
import com.king.dubbo.entities.model.wx.WxTemplateInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxTemplateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(String temkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxTemplateInfo> selectByExampleWithBLOBs(WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxTemplateInfo> selectByExample(WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxTemplateInfo selectByPrimaryKey(String temkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxTemplateInfo record, @Param("example") WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") WxTemplateInfo record, @Param("example") WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxTemplateInfo record, @Param("example") WxTemplateInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(WxTemplateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxTemplateInfo record);
}