package com.king.dubbo.weixin.dao;


import com.king.dubbo.entities.model.wx.WxUserInfo;
import com.king.dubbo.entities.model.wx.WxUserInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxUserInfo> selectByExample(WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxUserInfo record, @Param("example") WxUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_wxfwh_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxUserInfo record);

    /**
     *@description  根据openid获取微信用户信息
     * @param openid
     * @return
     */
    WxUserInfo getWxUserByOpenId(String openid);
}