package com.king.dubbo.weixin.dao;

import com.king.dubbo.entities.model.wx.WxVideo;
import com.king.dubbo.entities.model.wx.WxVideoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface WxVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxVideo> selectByExample(WxVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxVideo record, @Param("example") WxVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxVideo record, @Param("example") WxVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_video
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxVideo record);
}