package com.king.dubbo.weixin.dao;

import java.util.List;

import com.king.dubbo.entities.model.wx.WxVoice;
import com.king.dubbo.entities.model.wx.WxVoiceExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WxVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int countByExample(WxVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByExample(WxVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insert(WxVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int insertSelective(WxVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    List<WxVoice> selectByExample(WxVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    WxVoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxVoice record, @Param("example") WxVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByExample(@Param("record") WxVoice record, @Param("example") WxVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(WxVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_voice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    int updateByPrimaryKey(WxVoice record);
}