package com.king.dubbo.dto;

import java.io.Serializable;
import java.util.Date;

public class AnimalHabitDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.eat
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String eat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.sleep
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String sleep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.plays
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String plays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.emotion
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String emotion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.create_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.update_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.dog_walking
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String dogWalking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Integer animalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column habit.wc_habits
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    private String wcHabits;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.id
     *
     * @return the value of habit.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.id
     *
     * @param id the value for habit.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.eat
     *
     * @return the value of habit.eat
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getEat() {
        return eat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.eat
     *
     * @param eat the value for habit.eat
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setEat(String eat) {
        this.eat = eat == null ? null : eat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.sleep
     *
     * @return the value of habit.sleep
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.sleep
     *
     * @param sleep the value for habit.sleep
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setSleep(String sleep) {
        this.sleep = sleep == null ? null : sleep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.plays
     *
     * @return the value of habit.plays
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getPlays() {
        return plays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.plays
     *
     * @param plays the value for habit.plays
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setPlays(String plays) {
        this.plays = plays == null ? null : plays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.emotion
     *
     * @return the value of habit.emotion
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getEmotion() {
        return emotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.emotion
     *
     * @param emotion the value for habit.emotion
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setEmotion(String emotion) {
        this.emotion = emotion == null ? null : emotion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.create_time
     *
     * @return the value of habit.create_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.create_time
     *
     * @param createTime the value for habit.create_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.update_time
     *
     * @return the value of habit.update_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.update_time
     *
     * @param updateTime the value for habit.update_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.dog_walking
     *
     * @return the value of habit.dog_walking
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getDogWalking() {
        return dogWalking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.dog_walking
     *
     * @param dogWalking the value for habit.dog_walking
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setDogWalking(String dogWalking) {
        this.dogWalking = dogWalking == null ? null : dogWalking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column habit.animal_id
     *
     * @return the value of habit.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Integer getAnimalId() {
        return animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column habit.animal_id
     *
     * @param animalId the value for habit.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setAnimalId(Integer animalId) {
        this.animalId = animalId;
    }

    public String getWcHabits() {
        return wcHabits;
    }

    public void setWcHabits(String wcHabits) {
        this.wcHabits = wcHabits;
    }
}