package com.king.dubbo.dto;

import java.io.Serializable;
import java.util.Date;

public class AnimalSeeRecordDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.cause
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String cause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.hospital
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.see_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Date seeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.see_status
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Integer seeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.create_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.update_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column see_record.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    private Integer animalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.id
     *
     * @return the value of see_record.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.id
     *
     * @param id the value for see_record.id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.cause
     *
     * @return the value of see_record.cause
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.cause
     *
     * @param cause the value for see_record.cause
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.hospital
     *
     * @return the value of see_record.hospital
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.hospital
     *
     * @param hospital the value for see_record.hospital
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.see_time
     *
     * @return the value of see_record.see_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Date getSeeTime() {
        return seeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.see_time
     *
     * @param seeTime the value for see_record.see_time
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setSeeTime(Date seeTime) {
        this.seeTime = seeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.see_status
     *
     * @return the value of see_record.see_status
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Integer getSeeStatus() {
        return seeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.see_status
     *
     * @param seeStatus the value for see_record.see_status
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setSeeStatus(Integer seeStatus) {
        this.seeStatus = seeStatus;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column see_record.animal_id
     *
     * @return the value of see_record.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public Integer getAnimalId() {
        return animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column see_record.animal_id
     *
     * @param animalId the value for see_record.animal_id
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    public void setAnimalId(Integer animalId) {
        this.animalId = animalId;
    }
}