package com.king.dubbo.dto;

import java.io.Serializable;

public class AnimalDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.catetory
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String catetory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.name
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.age
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.personalit
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String personalit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.status
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.sex
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.mother
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String mother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.father
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String father;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.create_time
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.update_time
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.image
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.user_id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    private Integer userId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.address
     *
     * @mbg.generated Sun Jun 23 09:13:14 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.arise_condition
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    private String ariseCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animals.type
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.id
     *
     * @return the value of animals.id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.id
     *
     * @param id the value for animals.id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.catetory
     *
     * @return the value of animals.catetory
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getCatetory() {
        return catetory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.catetory
     *
     * @param catetory the value for animals.catetory
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setCatetory(String catetory) {
        this.catetory = catetory == null ? null : catetory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.name
     *
     * @return the value of animals.name
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.name
     *
     * @param name the value for animals.name
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.age
     *
     * @return the value of animals.age
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.age
     *
     * @param age the value for animals.age
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.personalit
     *
     * @return the value of animals.personalit
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getPersonalit() {
        return personalit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.personalit
     *
     * @param personalit the value for animals.personalit
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setPersonalit(String personalit) {
        this.personalit = personalit == null ? null : personalit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.status
     *
     * @return the value of animals.status
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.status
     *
     * @param status the value for animals.status
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.sex
     *
     * @return the value of animals.sex
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.sex
     *
     * @param sex the value for animals.sex
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.mother
     *
     * @return the value of animals.mother
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getMother() {
        return mother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.mother
     *
     * @param mother the value for animals.mother
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setMother(String mother) {
        this.mother = mother == null ? null : mother.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.father
     *
     * @return the value of animals.father
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getFather() {
        return father;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.father
     *
     * @param father the value for animals.father
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setFather(String father) {
        this.father = father == null ? null : father.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.image
     *
     * @return the value of animals.image
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.image
     *
     * @param image the value for animals.image
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animals.user_id
     *
     * @return the value of animals.user_id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animals.user_id
     *
     * @param userId the value for animals.user_id
     *
     * @mbg.generated Sun Jun 16 15:11:46 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAriseCondition() {
        return ariseCondition;
    }

    public void setAriseCondition(String ariseCondition) {
        this.ariseCondition = ariseCondition;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "AnimalDto{" +
                "id=" + id +
                ", catetory='" + catetory + '\'' +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", personalit='" + personalit + '\'' +
                ", status=" + status +
                ", sex='" + sex + '\'' +
                ", mother='" + mother + '\'' +
                ", father='" + father + '\'' +
                ", createTime='" + createTime + '\'' +
                ", updateTime='" + updateTime + '\'' +
                ", image='" + image + '\'' +
                ", userId=" + userId +
                ", address='" + address + '\'' +
                ", ariseCondition='" + ariseCondition + '\'' +
                ", type=" + type +
                '}';
    }
}
