package com.king.dubbo.entities.model.wx;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxActivityAwardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public WxActivityAwardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAwardTextIsNull() {
            addCriterion("award_text is null");
            return (Criteria) this;
        }

        public Criteria andAwardTextIsNotNull() {
            addCriterion("award_text is not null");
            return (Criteria) this;
        }

        public Criteria andAwardTextEqualTo(String value) {
            addCriterion("award_text =", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextNotEqualTo(String value) {
            addCriterion("award_text <>", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextGreaterThan(String value) {
            addCriterion("award_text >", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextGreaterThanOrEqualTo(String value) {
            addCriterion("award_text >=", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextLessThan(String value) {
            addCriterion("award_text <", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextLessThanOrEqualTo(String value) {
            addCriterion("award_text <=", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextLike(String value) {
            addCriterion("award_text like", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextNotLike(String value) {
            addCriterion("award_text not like", value, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextIn(List<String> values) {
            addCriterion("award_text in", values, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextNotIn(List<String> values) {
            addCriterion("award_text not in", values, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextBetween(String value1, String value2) {
            addCriterion("award_text between", value1, value2, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardTextNotBetween(String value1, String value2) {
            addCriterion("award_text not between", value1, value2, "awardText");
            return (Criteria) this;
        }

        public Criteria andAwardContentIsNull() {
            addCriterion("award_content is null");
            return (Criteria) this;
        }

        public Criteria andAwardContentIsNotNull() {
            addCriterion("award_content is not null");
            return (Criteria) this;
        }

        public Criteria andAwardContentEqualTo(String value) {
            addCriterion("award_content =", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentNotEqualTo(String value) {
            addCriterion("award_content <>", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentGreaterThan(String value) {
            addCriterion("award_content >", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentGreaterThanOrEqualTo(String value) {
            addCriterion("award_content >=", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentLessThan(String value) {
            addCriterion("award_content <", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentLessThanOrEqualTo(String value) {
            addCriterion("award_content <=", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentLike(String value) {
            addCriterion("award_content like", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentNotLike(String value) {
            addCriterion("award_content not like", value, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentIn(List<String> values) {
            addCriterion("award_content in", values, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentNotIn(List<String> values) {
            addCriterion("award_content not in", values, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentBetween(String value1, String value2) {
            addCriterion("award_content between", value1, value2, "awardContent");
            return (Criteria) this;
        }

        public Criteria andAwardContentNotBetween(String value1, String value2) {
            addCriterion("award_content not between", value1, value2, "awardContent");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIsNull() {
            addCriterion("undate_time is null");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIsNotNull() {
            addCriterion("undate_time is not null");
            return (Criteria) this;
        }

        public Criteria andUndateTimeEqualTo(Date value) {
            addCriterion("undate_time =", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotEqualTo(Date value) {
            addCriterion("undate_time <>", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeGreaterThan(Date value) {
            addCriterion("undate_time >", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("undate_time >=", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeLessThan(Date value) {
            addCriterion("undate_time <", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeLessThanOrEqualTo(Date value) {
            addCriterion("undate_time <=", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIn(List<Date> values) {
            addCriterion("undate_time in", values, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotIn(List<Date> values) {
            addCriterion("undate_time not in", values, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeBetween(Date value1, Date value2) {
            addCriterion("undate_time between", value1, value2, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotBetween(Date value1, Date value2) {
            addCriterion("undate_time not between", value1, value2, "undateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIsNull() {
            addCriterion("activity_code is null");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIsNotNull() {
            addCriterion("activity_code is not null");
            return (Criteria) this;
        }

        public Criteria andActivityCodeEqualTo(String value) {
            addCriterion("activity_code =", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotEqualTo(String value) {
            addCriterion("activity_code <>", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeGreaterThan(String value) {
            addCriterion("activity_code >", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("activity_code >=", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLessThan(String value) {
            addCriterion("activity_code <", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLessThanOrEqualTo(String value) {
            addCriterion("activity_code <=", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeLike(String value) {
            addCriterion("activity_code like", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotLike(String value) {
            addCriterion("activity_code not like", value, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeIn(List<String> values) {
            addCriterion("activity_code in", values, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotIn(List<String> values) {
            addCriterion("activity_code not in", values, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeBetween(String value1, String value2) {
            addCriterion("activity_code between", value1, value2, "activityCode");
            return (Criteria) this;
        }

        public Criteria andActivityCodeNotBetween(String value1, String value2) {
            addCriterion("activity_code not between", value1, value2, "activityCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 28 01:23:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_award
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}