package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxActivityAward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.award_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String awardText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.award_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String awardContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date undateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_award.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String activityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.id
     *
     * @return the value of wxfwh_reply_award.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.id
     *
     * @param id the value for wxfwh_reply_award.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.award_text
     *
     * @return the value of wxfwh_reply_award.award_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getAwardText() {
        return awardText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.award_text
     *
     * @param awardText the value for wxfwh_reply_award.award_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setAwardText(String awardText) {
        this.awardText = awardText == null ? null : awardText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.award_content
     *
     * @return the value of wxfwh_reply_award.award_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getAwardContent() {
        return awardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.award_content
     *
     * @param awardContent the value for wxfwh_reply_award.award_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setAwardContent(String awardContent) {
        this.awardContent = awardContent == null ? null : awardContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.creat_time
     *
     * @return the value of wxfwh_reply_award.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.creat_time
     *
     * @param creatTime the value for wxfwh_reply_award.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.undate_time
     *
     * @return the value of wxfwh_reply_award.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUndateTime() {
        return undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.undate_time
     *
     * @param undateTime the value for wxfwh_reply_award.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUndateTime(Date undateTime) {
        this.undateTime = undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.remark
     *
     * @return the value of wxfwh_reply_award.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.remark
     *
     * @param remark the value for wxfwh_reply_award.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_award.activity_code
     *
     * @return the value of wxfwh_reply_award.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_award.activity_code
     *
     * @param activityCode the value for wxfwh_reply_award.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }
}