package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxActivityCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.open_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.user_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String activityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.create_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_count.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.id
     *
     * @return the value of wxfwh_activity_count.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.id
     *
     * @param id the value for wxfwh_activity_count.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.open_Id
     *
     * @return the value of wxfwh_activity_count.open_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.open_Id
     *
     * @param openId the value for wxfwh_activity_count.open_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.user_Id
     *
     * @return the value of wxfwh_activity_count.user_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.user_Id
     *
     * @param userId the value for wxfwh_activity_count.user_Id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.activity_code
     *
     * @return the value of wxfwh_activity_count.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.activity_code
     *
     * @param activityCode the value for wxfwh_activity_count.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.activity_name
     *
     * @return the value of wxfwh_activity_count.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.activity_name
     *
     * @param activityName the value for wxfwh_activity_count.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.count
     *
     * @return the value of wxfwh_activity_count.count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.count
     *
     * @param count the value for wxfwh_activity_count.count
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.create_time
     *
     * @return the value of wxfwh_activity_count.create_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.create_time
     *
     * @param createTime the value for wxfwh_activity_count.create_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.update_time
     *
     * @return the value of wxfwh_activity_count.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.update_time
     *
     * @param updateTime the value for wxfwh_activity_count.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_count.remark
     *
     * @return the value of wxfwh_activity_count.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_count.remark
     *
     * @param remark the value for wxfwh_activity_count.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}