package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxArticleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.title
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.description
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.picurl
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.url
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.news_code
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String newsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.creat_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.undate_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Date undateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.remark
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.thum_media_id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String thumMediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.author
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.content
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.digest
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.show_cover_pic
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Integer showCoverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.need_open_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Integer needOpenComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news_article_info.only_fans_can_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    private Integer onlyFansCanComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.id
     *
     * @return the value of wxfwh_reply_news_article_info.id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.id
     *
     * @param id the value for wxfwh_reply_news_article_info.id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.title
     *
     * @return the value of wxfwh_reply_news_article_info.title
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.title
     *
     * @param title the value for wxfwh_reply_news_article_info.title
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.description
     *
     * @return the value of wxfwh_reply_news_article_info.description
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.description
     *
     * @param description the value for wxfwh_reply_news_article_info.description
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.picurl
     *
     * @return the value of wxfwh_reply_news_article_info.picurl
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.picurl
     *
     * @param picurl the value for wxfwh_reply_news_article_info.picurl
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.url
     *
     * @return the value of wxfwh_reply_news_article_info.url
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.url
     *
     * @param url the value for wxfwh_reply_news_article_info.url
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.news_code
     *
     * @return the value of wxfwh_reply_news_article_info.news_code
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getNewsCode() {
        return newsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.news_code
     *
     * @param newsCode the value for wxfwh_reply_news_article_info.news_code
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setNewsCode(String newsCode) {
        this.newsCode = newsCode == null ? null : newsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.creat_time
     *
     * @return the value of wxfwh_reply_news_article_info.creat_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.creat_time
     *
     * @param creatTime the value for wxfwh_reply_news_article_info.creat_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.undate_time
     *
     * @return the value of wxfwh_reply_news_article_info.undate_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Date getUndateTime() {
        return undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.undate_time
     *
     * @param undateTime the value for wxfwh_reply_news_article_info.undate_time
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setUndateTime(Date undateTime) {
        this.undateTime = undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.remark
     *
     * @return the value of wxfwh_reply_news_article_info.remark
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.remark
     *
     * @param remark the value for wxfwh_reply_news_article_info.remark
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.thum_media_id
     *
     * @return the value of wxfwh_reply_news_article_info.thum_media_id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getThumMediaId() {
        return thumMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.thum_media_id
     *
     * @param thumMediaId the value for wxfwh_reply_news_article_info.thum_media_id
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setThumMediaId(String thumMediaId) {
        this.thumMediaId = thumMediaId == null ? null : thumMediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.author
     *
     * @return the value of wxfwh_reply_news_article_info.author
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.author
     *
     * @param author the value for wxfwh_reply_news_article_info.author
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.content
     *
     * @return the value of wxfwh_reply_news_article_info.content
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.content
     *
     * @param content the value for wxfwh_reply_news_article_info.content
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.digest
     *
     * @return the value of wxfwh_reply_news_article_info.digest
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.digest
     *
     * @param digest the value for wxfwh_reply_news_article_info.digest
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setDigest(String digest) {
        this.digest = digest == null ? null : digest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.show_cover_pic
     *
     * @return the value of wxfwh_reply_news_article_info.show_cover_pic
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Integer getShowCoverPic() {
        return showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.show_cover_pic
     *
     * @param showCoverPic the value for wxfwh_reply_news_article_info.show_cover_pic
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setShowCoverPic(Integer showCoverPic) {
        this.showCoverPic = showCoverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.need_open_comment
     *
     * @return the value of wxfwh_reply_news_article_info.need_open_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Integer getNeedOpenComment() {
        return needOpenComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.need_open_comment
     *
     * @param needOpenComment the value for wxfwh_reply_news_article_info.need_open_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setNeedOpenComment(Integer needOpenComment) {
        this.needOpenComment = needOpenComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news_article_info.only_fans_can_comment
     *
     * @return the value of wxfwh_reply_news_article_info.only_fans_can_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Integer getOnlyFansCanComment() {
        return onlyFansCanComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news_article_info.only_fans_can_comment
     *
     * @param onlyFansCanComment the value for wxfwh_reply_news_article_info.only_fans_can_comment
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setOnlyFansCanComment(Integer onlyFansCanComment) {
        this.onlyFansCanComment = onlyFansCanComment;
    }
}