package com.king.dubbo.entities.model.wx;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxArticleInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public WxArticleInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNull() {
            addCriterion("picurl is null");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNotNull() {
            addCriterion("picurl is not null");
            return (Criteria) this;
        }

        public Criteria andPicurlEqualTo(String value) {
            addCriterion("picurl =", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotEqualTo(String value) {
            addCriterion("picurl <>", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThan(String value) {
            addCriterion("picurl >", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("picurl >=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThan(String value) {
            addCriterion("picurl <", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThanOrEqualTo(String value) {
            addCriterion("picurl <=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLike(String value) {
            addCriterion("picurl like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotLike(String value) {
            addCriterion("picurl not like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlIn(List<String> values) {
            addCriterion("picurl in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotIn(List<String> values) {
            addCriterion("picurl not in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlBetween(String value1, String value2) {
            addCriterion("picurl between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotBetween(String value1, String value2) {
            addCriterion("picurl not between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andNewsCodeIsNull() {
            addCriterion("news_code is null");
            return (Criteria) this;
        }

        public Criteria andNewsCodeIsNotNull() {
            addCriterion("news_code is not null");
            return (Criteria) this;
        }

        public Criteria andNewsCodeEqualTo(String value) {
            addCriterion("news_code =", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeNotEqualTo(String value) {
            addCriterion("news_code <>", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeGreaterThan(String value) {
            addCriterion("news_code >", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("news_code >=", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeLessThan(String value) {
            addCriterion("news_code <", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeLessThanOrEqualTo(String value) {
            addCriterion("news_code <=", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeLike(String value) {
            addCriterion("news_code like", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeNotLike(String value) {
            addCriterion("news_code not like", value, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeIn(List<String> values) {
            addCriterion("news_code in", values, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeNotIn(List<String> values) {
            addCriterion("news_code not in", values, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeBetween(String value1, String value2) {
            addCriterion("news_code between", value1, value2, "newsCode");
            return (Criteria) this;
        }

        public Criteria andNewsCodeNotBetween(String value1, String value2) {
            addCriterion("news_code not between", value1, value2, "newsCode");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIsNull() {
            addCriterion("undate_time is null");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIsNotNull() {
            addCriterion("undate_time is not null");
            return (Criteria) this;
        }

        public Criteria andUndateTimeEqualTo(Date value) {
            addCriterion("undate_time =", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotEqualTo(Date value) {
            addCriterion("undate_time <>", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeGreaterThan(Date value) {
            addCriterion("undate_time >", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("undate_time >=", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeLessThan(Date value) {
            addCriterion("undate_time <", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeLessThanOrEqualTo(Date value) {
            addCriterion("undate_time <=", value, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeIn(List<Date> values) {
            addCriterion("undate_time in", values, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotIn(List<Date> values) {
            addCriterion("undate_time not in", values, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeBetween(Date value1, Date value2) {
            addCriterion("undate_time between", value1, value2, "undateTime");
            return (Criteria) this;
        }

        public Criteria andUndateTimeNotBetween(Date value1, Date value2) {
            addCriterion("undate_time not between", value1, value2, "undateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdIsNull() {
            addCriterion("thum_media_id is null");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdIsNotNull() {
            addCriterion("thum_media_id is not null");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdEqualTo(String value) {
            addCriterion("thum_media_id =", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdNotEqualTo(String value) {
            addCriterion("thum_media_id <>", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdGreaterThan(String value) {
            addCriterion("thum_media_id >", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdGreaterThanOrEqualTo(String value) {
            addCriterion("thum_media_id >=", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdLessThan(String value) {
            addCriterion("thum_media_id <", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdLessThanOrEqualTo(String value) {
            addCriterion("thum_media_id <=", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdLike(String value) {
            addCriterion("thum_media_id like", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdNotLike(String value) {
            addCriterion("thum_media_id not like", value, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdIn(List<String> values) {
            addCriterion("thum_media_id in", values, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdNotIn(List<String> values) {
            addCriterion("thum_media_id not in", values, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdBetween(String value1, String value2) {
            addCriterion("thum_media_id between", value1, value2, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andThumMediaIdNotBetween(String value1, String value2) {
            addCriterion("thum_media_id not between", value1, value2, "thumMediaId");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andDigestIsNull() {
            addCriterion("digest is null");
            return (Criteria) this;
        }

        public Criteria andDigestIsNotNull() {
            addCriterion("digest is not null");
            return (Criteria) this;
        }

        public Criteria andDigestEqualTo(String value) {
            addCriterion("digest =", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotEqualTo(String value) {
            addCriterion("digest <>", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThan(String value) {
            addCriterion("digest >", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestGreaterThanOrEqualTo(String value) {
            addCriterion("digest >=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThan(String value) {
            addCriterion("digest <", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLessThanOrEqualTo(String value) {
            addCriterion("digest <=", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestLike(String value) {
            addCriterion("digest like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotLike(String value) {
            addCriterion("digest not like", value, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestIn(List<String> values) {
            addCriterion("digest in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotIn(List<String> values) {
            addCriterion("digest not in", values, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestBetween(String value1, String value2) {
            addCriterion("digest between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andDigestNotBetween(String value1, String value2) {
            addCriterion("digest not between", value1, value2, "digest");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIsNull() {
            addCriterion("show_cover_pic is null");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIsNotNull() {
            addCriterion("show_cover_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicEqualTo(Integer value) {
            addCriterion("show_cover_pic =", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotEqualTo(Integer value) {
            addCriterion("show_cover_pic <>", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicGreaterThan(Integer value) {
            addCriterion("show_cover_pic >", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_cover_pic >=", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicLessThan(Integer value) {
            addCriterion("show_cover_pic <", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicLessThanOrEqualTo(Integer value) {
            addCriterion("show_cover_pic <=", value, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicIn(List<Integer> values) {
            addCriterion("show_cover_pic in", values, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotIn(List<Integer> values) {
            addCriterion("show_cover_pic not in", values, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicBetween(Integer value1, Integer value2) {
            addCriterion("show_cover_pic between", value1, value2, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andShowCoverPicNotBetween(Integer value1, Integer value2) {
            addCriterion("show_cover_pic not between", value1, value2, "showCoverPic");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentIsNull() {
            addCriterion("need_open_comment is null");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentIsNotNull() {
            addCriterion("need_open_comment is not null");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentEqualTo(Integer value) {
            addCriterion("need_open_comment =", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentNotEqualTo(Integer value) {
            addCriterion("need_open_comment <>", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentGreaterThan(Integer value) {
            addCriterion("need_open_comment >", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_open_comment >=", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentLessThan(Integer value) {
            addCriterion("need_open_comment <", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentLessThanOrEqualTo(Integer value) {
            addCriterion("need_open_comment <=", value, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentIn(List<Integer> values) {
            addCriterion("need_open_comment in", values, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentNotIn(List<Integer> values) {
            addCriterion("need_open_comment not in", values, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentBetween(Integer value1, Integer value2) {
            addCriterion("need_open_comment between", value1, value2, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andNeedOpenCommentNotBetween(Integer value1, Integer value2) {
            addCriterion("need_open_comment not between", value1, value2, "needOpenComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentIsNull() {
            addCriterion("only_fans_can_comment is null");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentIsNotNull() {
            addCriterion("only_fans_can_comment is not null");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentEqualTo(Integer value) {
            addCriterion("only_fans_can_comment =", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentNotEqualTo(Integer value) {
            addCriterion("only_fans_can_comment <>", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentGreaterThan(Integer value) {
            addCriterion("only_fans_can_comment >", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentGreaterThanOrEqualTo(Integer value) {
            addCriterion("only_fans_can_comment >=", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentLessThan(Integer value) {
            addCriterion("only_fans_can_comment <", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentLessThanOrEqualTo(Integer value) {
            addCriterion("only_fans_can_comment <=", value, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentIn(List<Integer> values) {
            addCriterion("only_fans_can_comment in", values, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentNotIn(List<Integer> values) {
            addCriterion("only_fans_can_comment not in", values, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentBetween(Integer value1, Integer value2) {
            addCriterion("only_fans_can_comment between", value1, value2, "onlyFansCanComment");
            return (Criteria) this;
        }

        public Criteria andOnlyFansCanCommentNotBetween(Integer value1, Integer value2) {
            addCriterion("only_fans_can_comment not between", value1, value2, "onlyFansCanComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 16 23:07:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_reply_news_article_info
     *
     * @mbggenerated Fri Nov 16 23:07:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}