package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxAssignmentActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String activityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.keyword_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String keywordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.keyword_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String keywordContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.reply_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String replyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.relation_id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.is_open
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.start_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.end_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_activity_assignment.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.id
     *
     * @return the value of wxfwh_activity_assignment.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.id
     *
     * @param id the value for wxfwh_activity_assignment.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.activity_code
     *
     * @return the value of wxfwh_activity_assignment.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.activity_code
     *
     * @param activityCode the value for wxfwh_activity_assignment.activity_code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.activity_name
     *
     * @return the value of wxfwh_activity_assignment.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.activity_name
     *
     * @param activityName the value for wxfwh_activity_assignment.activity_name
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.keyword_type
     *
     * @return the value of wxfwh_activity_assignment.keyword_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getKeywordType() {
        return keywordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.keyword_type
     *
     * @param keywordType the value for wxfwh_activity_assignment.keyword_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setKeywordType(String keywordType) {
        this.keywordType = keywordType == null ? null : keywordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.keyword_content
     *
     * @return the value of wxfwh_activity_assignment.keyword_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getKeywordContent() {
        return keywordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.keyword_content
     *
     * @param keywordContent the value for wxfwh_activity_assignment.keyword_content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setKeywordContent(String keywordContent) {
        this.keywordContent = keywordContent == null ? null : keywordContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.reply_type
     *
     * @return the value of wxfwh_activity_assignment.reply_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.reply_type
     *
     * @param replyType the value for wxfwh_activity_assignment.reply_type
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setReplyType(String replyType) {
        this.replyType = replyType == null ? null : replyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.relation_id
     *
     * @return the value of wxfwh_activity_assignment.relation_id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.relation_id
     *
     * @param relationId the value for wxfwh_activity_assignment.relation_id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.is_open
     *
     * @return the value of wxfwh_activity_assignment.is_open
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.is_open
     *
     * @param isOpen the value for wxfwh_activity_assignment.is_open
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setIsOpen(String isOpen) {
        this.isOpen = isOpen == null ? null : isOpen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.start_time
     *
     * @return the value of wxfwh_activity_assignment.start_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.start_time
     *
     * @param startTime the value for wxfwh_activity_assignment.start_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.end_time
     *
     * @return the value of wxfwh_activity_assignment.end_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.end_time
     *
     * @param endTime the value for wxfwh_activity_assignment.end_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.creat_time
     *
     * @return the value of wxfwh_activity_assignment.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.creat_time
     *
     * @param creatTime the value for wxfwh_activity_assignment.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.update_time
     *
     * @return the value of wxfwh_activity_assignment.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.update_time
     *
     * @param updateTime the value for wxfwh_activity_assignment.update_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_activity_assignment.remark
     *
     * @return the value of wxfwh_activity_assignment.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_activity_assignment.remark
     *
     * @param remark the value for wxfwh_activity_assignment.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}