package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxMenuConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.parent_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.name
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.level
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.type
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.relation_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Integer relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.creat_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.update_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.state
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_menu_config.content
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.id
     *
     * @return the value of wxfwh_menu_config.id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.id
     *
     * @param id the value for wxfwh_menu_config.id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.parent_id
     *
     * @return the value of wxfwh_menu_config.parent_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.parent_id
     *
     * @param parentId the value for wxfwh_menu_config.parent_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.name
     *
     * @return the value of wxfwh_menu_config.name
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.name
     *
     * @param name the value for wxfwh_menu_config.name
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.level
     *
     * @return the value of wxfwh_menu_config.level
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.level
     *
     * @param level the value for wxfwh_menu_config.level
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.type
     *
     * @return the value of wxfwh_menu_config.type
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.type
     *
     * @param type the value for wxfwh_menu_config.type
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.relation_id
     *
     * @return the value of wxfwh_menu_config.relation_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.relation_id
     *
     * @param relationId the value for wxfwh_menu_config.relation_id
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.creat_time
     *
     * @return the value of wxfwh_menu_config.creat_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.creat_time
     *
     * @param creatTime the value for wxfwh_menu_config.creat_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.update_time
     *
     * @return the value of wxfwh_menu_config.update_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.update_time
     *
     * @param updateTime the value for wxfwh_menu_config.update_time
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.state
     *
     * @return the value of wxfwh_menu_config.state
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.state
     *
     * @param state the value for wxfwh_menu_config.state
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_menu_config.content
     *
     * @return the value of wxfwh_menu_config.content
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_menu_config.content
     *
     * @param content the value for wxfwh_menu_config.content
     *
     * @mbggenerated Sat Nov 10 12:06:32 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}