package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news.code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date undateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_news.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news.id
     *
     * @return the value of wxfwh_reply_news.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news.id
     *
     * @param id the value for wxfwh_reply_news.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news.code
     *
     * @return the value of wxfwh_reply_news.code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news.code
     *
     * @param code the value for wxfwh_reply_news.code
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news.creat_time
     *
     * @return the value of wxfwh_reply_news.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news.creat_time
     *
     * @param creatTime the value for wxfwh_reply_news.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news.undate_time
     *
     * @return the value of wxfwh_reply_news.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUndateTime() {
        return undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news.undate_time
     *
     * @param undateTime the value for wxfwh_reply_news.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUndateTime(Date undateTime) {
        this.undateTime = undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_news.remark
     *
     * @return the value of wxfwh_reply_news.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_news.remark
     *
     * @param remark the value for wxfwh_reply_news.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}