package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxReplyTemplateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.bind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String bindTemplateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.unbind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String unbindTemplateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date undateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_template.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.id
     *
     * @return the value of wxfwh_reply_template.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.id
     *
     * @param id the value for wxfwh_reply_template.id
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.bind_template_key
     *
     * @return the value of wxfwh_reply_template.bind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getBindTemplateKey() {
        return bindTemplateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.bind_template_key
     *
     * @param bindTemplateKey the value for wxfwh_reply_template.bind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setBindTemplateKey(String bindTemplateKey) {
        this.bindTemplateKey = bindTemplateKey == null ? null : bindTemplateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.unbind_template_key
     *
     * @return the value of wxfwh_reply_template.unbind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getUnbindTemplateKey() {
        return unbindTemplateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.unbind_template_key
     *
     * @param unbindTemplateKey the value for wxfwh_reply_template.unbind_template_key
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUnbindTemplateKey(String unbindTemplateKey) {
        this.unbindTemplateKey = unbindTemplateKey == null ? null : unbindTemplateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.creat_time
     *
     * @return the value of wxfwh_reply_template.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.creat_time
     *
     * @param creatTime the value for wxfwh_reply_template.creat_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.undate_time
     *
     * @return the value of wxfwh_reply_template.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUndateTime() {
        return undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.undate_time
     *
     * @param undateTime the value for wxfwh_reply_template.undate_time
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUndateTime(Date undateTime) {
        this.undateTime = undateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_template.remark
     *
     * @return the value of wxfwh_reply_template.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_template.remark
     *
     * @param remark the value for wxfwh_reply_template.remark
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}