package com.king.dubbo.entities.model.wx;

import java.util.Date;

public class WxTemplateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.temKey
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String temkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.templateId
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.title
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.primaryIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String primaryindustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.deputyIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String deputyindustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.example
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String example;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.source
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.firstNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String firstnotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.remarkNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String remarknotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.updateTime
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_template_info.url
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.temKey
     *
     * @return the value of wxfwh_template_info.temKey
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getTemkey() {
        return temkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.temKey
     *
     * @param temkey the value for wxfwh_template_info.temKey
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setTemkey(String temkey) {
        this.temkey = temkey == null ? null : temkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.templateId
     *
     * @return the value of wxfwh_template_info.templateId
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.templateId
     *
     * @param templateid the value for wxfwh_template_info.templateId
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setTemplateid(String templateid) {
        this.templateid = templateid == null ? null : templateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.title
     *
     * @return the value of wxfwh_template_info.title
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.title
     *
     * @param title the value for wxfwh_template_info.title
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.primaryIndustry
     *
     * @return the value of wxfwh_template_info.primaryIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getPrimaryindustry() {
        return primaryindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.primaryIndustry
     *
     * @param primaryindustry the value for wxfwh_template_info.primaryIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setPrimaryindustry(String primaryindustry) {
        this.primaryindustry = primaryindustry == null ? null : primaryindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.deputyIndustry
     *
     * @return the value of wxfwh_template_info.deputyIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getDeputyindustry() {
        return deputyindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.deputyIndustry
     *
     * @param deputyindustry the value for wxfwh_template_info.deputyIndustry
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setDeputyindustry(String deputyindustry) {
        this.deputyindustry = deputyindustry == null ? null : deputyindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.content
     *
     * @return the value of wxfwh_template_info.content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.content
     *
     * @param content the value for wxfwh_template_info.content
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.example
     *
     * @return the value of wxfwh_template_info.example
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.example
     *
     * @param example the value for wxfwh_template_info.example
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.source
     *
     * @return the value of wxfwh_template_info.source
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.source
     *
     * @param source the value for wxfwh_template_info.source
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.firstNotice
     *
     * @return the value of wxfwh_template_info.firstNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getFirstnotice() {
        return firstnotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.firstNotice
     *
     * @param firstnotice the value for wxfwh_template_info.firstNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setFirstnotice(String firstnotice) {
        this.firstnotice = firstnotice == null ? null : firstnotice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.remarkNotice
     *
     * @return the value of wxfwh_template_info.remarkNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getRemarknotice() {
        return remarknotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.remarkNotice
     *
     * @param remarknotice the value for wxfwh_template_info.remarkNotice
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setRemarknotice(String remarknotice) {
        this.remarknotice = remarknotice == null ? null : remarknotice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.updateTime
     *
     * @return the value of wxfwh_template_info.updateTime
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.updateTime
     *
     * @param updatetime the value for wxfwh_template_info.updateTime
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_template_info.url
     *
     * @return the value of wxfwh_template_info.url
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_template_info.url
     *
     * @param url the value for wxfwh_template_info.url
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}