package com.king.dubbo.entities.model.wx;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxTemplateInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public WxTemplateInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTemkeyIsNull() {
            addCriterion("temKey is null");
            return (Criteria) this;
        }

        public Criteria andTemkeyIsNotNull() {
            addCriterion("temKey is not null");
            return (Criteria) this;
        }

        public Criteria andTemkeyEqualTo(String value) {
            addCriterion("temKey =", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyNotEqualTo(String value) {
            addCriterion("temKey <>", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyGreaterThan(String value) {
            addCriterion("temKey >", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyGreaterThanOrEqualTo(String value) {
            addCriterion("temKey >=", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyLessThan(String value) {
            addCriterion("temKey <", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyLessThanOrEqualTo(String value) {
            addCriterion("temKey <=", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyLike(String value) {
            addCriterion("temKey like", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyNotLike(String value) {
            addCriterion("temKey not like", value, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyIn(List<String> values) {
            addCriterion("temKey in", values, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyNotIn(List<String> values) {
            addCriterion("temKey not in", values, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyBetween(String value1, String value2) {
            addCriterion("temKey between", value1, value2, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemkeyNotBetween(String value1, String value2) {
            addCriterion("temKey not between", value1, value2, "temkey");
            return (Criteria) this;
        }

        public Criteria andTemplateidIsNull() {
            addCriterion("templateId is null");
            return (Criteria) this;
        }

        public Criteria andTemplateidIsNotNull() {
            addCriterion("templateId is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateidEqualTo(String value) {
            addCriterion("templateId =", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidNotEqualTo(String value) {
            addCriterion("templateId <>", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidGreaterThan(String value) {
            addCriterion("templateId >", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidGreaterThanOrEqualTo(String value) {
            addCriterion("templateId >=", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidLessThan(String value) {
            addCriterion("templateId <", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidLessThanOrEqualTo(String value) {
            addCriterion("templateId <=", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidLike(String value) {
            addCriterion("templateId like", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidNotLike(String value) {
            addCriterion("templateId not like", value, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidIn(List<String> values) {
            addCriterion("templateId in", values, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidNotIn(List<String> values) {
            addCriterion("templateId not in", values, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidBetween(String value1, String value2) {
            addCriterion("templateId between", value1, value2, "templateid");
            return (Criteria) this;
        }

        public Criteria andTemplateidNotBetween(String value1, String value2) {
            addCriterion("templateId not between", value1, value2, "templateid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryIsNull() {
            addCriterion("primaryIndustry is null");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryIsNotNull() {
            addCriterion("primaryIndustry is not null");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryEqualTo(String value) {
            addCriterion("primaryIndustry =", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryNotEqualTo(String value) {
            addCriterion("primaryIndustry <>", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryGreaterThan(String value) {
            addCriterion("primaryIndustry >", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryGreaterThanOrEqualTo(String value) {
            addCriterion("primaryIndustry >=", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryLessThan(String value) {
            addCriterion("primaryIndustry <", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryLessThanOrEqualTo(String value) {
            addCriterion("primaryIndustry <=", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryLike(String value) {
            addCriterion("primaryIndustry like", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryNotLike(String value) {
            addCriterion("primaryIndustry not like", value, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryIn(List<String> values) {
            addCriterion("primaryIndustry in", values, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryNotIn(List<String> values) {
            addCriterion("primaryIndustry not in", values, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryBetween(String value1, String value2) {
            addCriterion("primaryIndustry between", value1, value2, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andPrimaryindustryNotBetween(String value1, String value2) {
            addCriterion("primaryIndustry not between", value1, value2, "primaryindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryIsNull() {
            addCriterion("deputyIndustry is null");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryIsNotNull() {
            addCriterion("deputyIndustry is not null");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryEqualTo(String value) {
            addCriterion("deputyIndustry =", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryNotEqualTo(String value) {
            addCriterion("deputyIndustry <>", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryGreaterThan(String value) {
            addCriterion("deputyIndustry >", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryGreaterThanOrEqualTo(String value) {
            addCriterion("deputyIndustry >=", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryLessThan(String value) {
            addCriterion("deputyIndustry <", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryLessThanOrEqualTo(String value) {
            addCriterion("deputyIndustry <=", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryLike(String value) {
            addCriterion("deputyIndustry like", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryNotLike(String value) {
            addCriterion("deputyIndustry not like", value, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryIn(List<String> values) {
            addCriterion("deputyIndustry in", values, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryNotIn(List<String> values) {
            addCriterion("deputyIndustry not in", values, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryBetween(String value1, String value2) {
            addCriterion("deputyIndustry between", value1, value2, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andDeputyindustryNotBetween(String value1, String value2) {
            addCriterion("deputyIndustry not between", value1, value2, "deputyindustry");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andExampleIsNull() {
            addCriterion("example is null");
            return (Criteria) this;
        }

        public Criteria andExampleIsNotNull() {
            addCriterion("example is not null");
            return (Criteria) this;
        }

        public Criteria andExampleEqualTo(String value) {
            addCriterion("example =", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotEqualTo(String value) {
            addCriterion("example <>", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleGreaterThan(String value) {
            addCriterion("example >", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleGreaterThanOrEqualTo(String value) {
            addCriterion("example >=", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLessThan(String value) {
            addCriterion("example <", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLessThanOrEqualTo(String value) {
            addCriterion("example <=", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleLike(String value) {
            addCriterion("example like", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotLike(String value) {
            addCriterion("example not like", value, "example");
            return (Criteria) this;
        }

        public Criteria andExampleIn(List<String> values) {
            addCriterion("example in", values, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotIn(List<String> values) {
            addCriterion("example not in", values, "example");
            return (Criteria) this;
        }

        public Criteria andExampleBetween(String value1, String value2) {
            addCriterion("example between", value1, value2, "example");
            return (Criteria) this;
        }

        public Criteria andExampleNotBetween(String value1, String value2) {
            addCriterion("example not between", value1, value2, "example");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeIsNull() {
            addCriterion("firstNotice is null");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeIsNotNull() {
            addCriterion("firstNotice is not null");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeEqualTo(String value) {
            addCriterion("firstNotice =", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeNotEqualTo(String value) {
            addCriterion("firstNotice <>", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeGreaterThan(String value) {
            addCriterion("firstNotice >", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeGreaterThanOrEqualTo(String value) {
            addCriterion("firstNotice >=", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeLessThan(String value) {
            addCriterion("firstNotice <", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeLessThanOrEqualTo(String value) {
            addCriterion("firstNotice <=", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeLike(String value) {
            addCriterion("firstNotice like", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeNotLike(String value) {
            addCriterion("firstNotice not like", value, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeIn(List<String> values) {
            addCriterion("firstNotice in", values, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeNotIn(List<String> values) {
            addCriterion("firstNotice not in", values, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeBetween(String value1, String value2) {
            addCriterion("firstNotice between", value1, value2, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andFirstnoticeNotBetween(String value1, String value2) {
            addCriterion("firstNotice not between", value1, value2, "firstnotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeIsNull() {
            addCriterion("remarkNotice is null");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeIsNotNull() {
            addCriterion("remarkNotice is not null");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeEqualTo(String value) {
            addCriterion("remarkNotice =", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeNotEqualTo(String value) {
            addCriterion("remarkNotice <>", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeGreaterThan(String value) {
            addCriterion("remarkNotice >", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeGreaterThanOrEqualTo(String value) {
            addCriterion("remarkNotice >=", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeLessThan(String value) {
            addCriterion("remarkNotice <", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeLessThanOrEqualTo(String value) {
            addCriterion("remarkNotice <=", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeLike(String value) {
            addCriterion("remarkNotice like", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeNotLike(String value) {
            addCriterion("remarkNotice not like", value, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeIn(List<String> values) {
            addCriterion("remarkNotice in", values, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeNotIn(List<String> values) {
            addCriterion("remarkNotice not in", values, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeBetween(String value1, String value2) {
            addCriterion("remarkNotice between", value1, value2, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andRemarknoticeNotBetween(String value1, String value2) {
            addCriterion("remarkNotice not between", value1, value2, "remarknotice");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 28 01:23:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wxfwh_template_info
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}