package com.king.dubbo.entities.model.wx;

public class WxTextWithBLOBs extends WxText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_text.bind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String bindFreeloginText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_text.unbind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String unbindFreeloginText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_text.bind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String bindUnfreeloginText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxfwh_reply_text.unbind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    private String unbindUnfreeloginText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_text.bind_freelogin_text
     *
     * @return the value of wxfwh_reply_text.bind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getBindFreeloginText() {
        return bindFreeloginText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_text.bind_freelogin_text
     *
     * @param bindFreeloginText the value for wxfwh_reply_text.bind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setBindFreeloginText(String bindFreeloginText) {
        this.bindFreeloginText = bindFreeloginText == null ? null : bindFreeloginText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_text.unbind_freelogin_text
     *
     * @return the value of wxfwh_reply_text.unbind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getUnbindFreeloginText() {
        return unbindFreeloginText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_text.unbind_freelogin_text
     *
     * @param unbindFreeloginText the value for wxfwh_reply_text.unbind_freelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUnbindFreeloginText(String unbindFreeloginText) {
        this.unbindFreeloginText = unbindFreeloginText == null ? null : unbindFreeloginText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_text.bind_unfreelogin_text
     *
     * @return the value of wxfwh_reply_text.bind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getBindUnfreeloginText() {
        return bindUnfreeloginText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_text.bind_unfreelogin_text
     *
     * @param bindUnfreeloginText the value for wxfwh_reply_text.bind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setBindUnfreeloginText(String bindUnfreeloginText) {
        this.bindUnfreeloginText = bindUnfreeloginText == null ? null : bindUnfreeloginText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxfwh_reply_text.unbind_unfreelogin_text
     *
     * @return the value of wxfwh_reply_text.unbind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public String getUnbindUnfreeloginText() {
        return unbindUnfreeloginText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxfwh_reply_text.unbind_unfreelogin_text
     *
     * @param unbindUnfreeloginText the value for wxfwh_reply_text.unbind_unfreelogin_text
     *
     * @mbggenerated Sun Oct 28 01:23:10 CST 2018
     */
    public void setUnbindUnfreeloginText(String unbindUnfreeloginText) {
        this.unbindUnfreeloginText = unbindUnfreeloginText == null ? null : unbindUnfreeloginText.trim();
    }
}