package com.king.dubbo.animal.dao;

import com.king.dubbo.animal.dao.model.AdoptCondition;
import com.king.dubbo.animal.dao.model.AdoptConditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdoptConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    long countByExample(AdoptConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int deleteByExample(AdoptConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int insert(AdoptCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int insertSelective(AdoptCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    List<AdoptCondition> selectByExample(AdoptConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    AdoptCondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdoptCondition record, @Param("example") AdoptConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int updateByExample(@Param("record") AdoptCondition record, @Param("example") AdoptConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int updateByPrimaryKeySelective(AdoptCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adopt_condition
     *
     * @mbg.generated Sat Jun 29 10:07:55 CST 2019
     */
    int updateByPrimaryKey(AdoptCondition record);

    /**
     * 获取所有的领养请求
     * @return
     */
    List<AdoptCondition> getAllAdoptCondition();
}