package com.king.dubbo.animal.dao;

import com.king.dubbo.animal.dao.model.AnimalSeeRecord;
import com.king.dubbo.animal.dao.model.AnimalSeeRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AnimalSeeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    long countByExample(AnimalSeeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int deleteByExample(AnimalSeeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int insert(AnimalSeeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int insertSelective(AnimalSeeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    List<AnimalSeeRecord> selectByExample(AnimalSeeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    AnimalSeeRecord selectByPrimaryKey(Integer id);

    List<AnimalSeeRecord> selectByAnimalId(Integer animalId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") AnimalSeeRecord record, @Param("example") AnimalSeeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int updateByExample(@Param("record") AnimalSeeRecord record, @Param("example") AnimalSeeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int updateByPrimaryKeySelective(AnimalSeeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table see_record
     *
     * @mbg.generated Tue Jun 18 23:38:54 CST 2019
     */
    int updateByPrimaryKey(AnimalSeeRecord record);
}