package com.king.dubbo.animal.dao;

import com.king.dubbo.animal.dao.model.Animal;
import com.king.dubbo.animal.dao.model.AnimalExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    long countByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int deleteByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int insert(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int insertSelective(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    List<Animal> selectByExample(AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    Animal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Animal record, @Param("example") AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByExample(@Param("record") Animal record, @Param("example") AnimalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByPrimaryKeySelective(Animal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table animals
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByPrimaryKey(Animal record);

    List<Animal>selectAnimalList();
}