package com.king.dubbo.animal.dao;

import com.king.dubbo.animal.dao.model.AnimalHabit;
import com.king.dubbo.animal.dao.model.AnimalHabitExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AnimalHabitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    long countByExample(AnimalHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int deleteByExample(AnimalHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int insert(AnimalHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int insertSelective(AnimalHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    List<AnimalHabit> selectByExample(AnimalHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    AnimalHabit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") AnimalHabit record, @Param("example") AnimalHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByExample(@Param("record") AnimalHabit record, @Param("example") AnimalHabitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByPrimaryKeySelective(AnimalHabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table habit
     *
     * @mbg.generated Thu Jun 27 22:40:32 CST 2019
     */
    int updateByPrimaryKey(AnimalHabit record);
}